feat: Apply button on individual signs matches groups
mbta/signs_ui pull request #584
Opened 2021-08-09 18:51 UTC by mkennedm

#### Summary of changes
**Asana Ticket:** [🔀 "apply" for both custom text modules functions similarly](https://app.asana.com/0/584764604969369/1200421875164011/f)

Apply button moved under date picker widget. Changes to sign takes effect after button is clicked. 

#### Reviewer Checklist
- [ ] Meets ticket's acceptance criteria
- [ ] Any new or changed functions have typespecs
- [ ] Tests were added for any new functionality (don't just rely on coverage statistics)
- [ ] This branch was deployed to the staging environment and is currently running with no unexpected increase in warnings, and no errors or crashes (compare on Splunk: [staging](https://mbta.splunkcloud.com/en-US/app/search/search?q=search%20index%3Dsigns-ui-dev%20%22%5Berror%5D%22%20OR%20%22%5Bwarn%5D%22%20OR%20%22CRASH%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-4h%40m&latest=now&sid=1545840769.3874970) vs. [prod](https://mbta.splunkcloud.com/en-US/app/search/search?q=search%20index%3Dsigns-ui-prod%20%22%5Berror%5D%22%20OR%20%22%5Bwarn%5D%22%20OR%20%22CRASH%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-4h%40m&latest=now&sid=1545840745.3874956))

2021-08-10 01:44 UTC, paulswartz requested changes
This takes care of Acceptance Criteria 2 (moves the apply button), but as far as I can see does not address either AC 1 or 3.

- selecting "Schedule return to Auto" > "at the end of an alert effect period" > an alert takes effect immediately (and shouldn't, AC 1)
- selecting "Custom" immediately takes effect (and shouldn't AC 3)

2021-08-10 13:07 UTC, mkennedm commented
> This takes care of Acceptance Criteria 2 (moves the apply button), but as far as I can see does not address either AC 1 or 3.
> 
> * selecting "Schedule return to Auto" > "at the end of an alert effect period" > an alert takes effect immediately (and shouldn't, AC 1)
> * selecting "Custom" immediately takes effect (and shouldn't, AC 3)

@paulswartz Sorry about this. The criteria was updated after I asked a question about it in Slack and I forgot to remove my request for review.

2021-08-12 14:07 UTC, losvedir commented
I slacked you these suggestions, but I'm going to post them here, too, so the PR reviewer has the context as well.

You'll have to refactor how the `SignPanel` component works.

React has the concept of "state", which is data that a component is responsible for internally, as opposed to "props" which is data that the component's parent gives it. What this ticket requires you to do is to move more stuff into the "state". Basically any changes that the component needs to know about that the rest of the app doesn't should be in the state.

Consider, as one part of this ticket, how changing the sign's mode from Auto -> Custom should open up the form without affecting the sign. Well, how did the component know whether or not to display the form beforehand?

```
{signConfig.mode === 'static_text' && !readOnly && !signGroup && (
  <div className="viewer--static-text-form">
    <div>
      <strong>Set custom message</strong>
    </div>
// ...
2:19 PM
this code only shows that markup if signConfig.mode === 'static_text'.  and what is signConfig?
2:19 PM
interface SignPanelProps {
  alerts: RouteAlerts;
  signId: string;
  modes: {
    auto: boolean;
    custom: boolean;
    headway: boolean;
    off: boolean;
  };
  signContent: SingleSignContent;
  currentTime: number;
  line: string;
  setConfigs: (x: SignConfigs) => void;
  signConfig: SignConfig;
  realtimeId: string;
  signGroup?: SignGroup;
  ungroupSign?: () => void;
  readOnly: boolean;
}
2:19 PM
it's one of the props of the component
2:21 PM
that's why currently the sign goes blank when you choose "custom".
2:21 PM
<select
  id={realtimeId}
  className="viewer--mode-select"
  value={signConfig.mode}
  onChange={(event) => {
    const newConfig = makeConfig(
      event.target.value as
        | 'auto'
        | 'headway'
        | 'off'
        | 'static_text',
    );
    this.setState({
      staticLine1: newConfig.line1 || '',
      staticLine2: newConfig.line2 || '',
      customChanges: false,
    });
    setConfigs({
      [realtimeId]: newConfig,
    });
  }}
>
2:22 PM
when the user chooses something in the <select> the onChange fires, which calls setConfigs(...) which sends a request to the backend.
2:25 PM
the flow of data goes from Phoenix backend -> ViewerApp -> ... -> Station -> SignPanel. and so selecting "custom" in the select updates the data in the backend, setting the sign's config to custom text with empty lines. and this data flows from the backend to the frontend and down the react app back to the SignPanel, and now the sign panel has in its props the fact that it's a custom text kind of sign, and so knows to display the form
2:27 PM
getting back to one of the changes of your ticket: setting the <select> to "custom" and not blanking the sign because those changes haven't taken affect yet: that means we have to short circuit this whole "send to the backend and have the data flow back down through the props" approach. instead the SignPanel will have to have in its own state something like a boolean displayForm. and so now when the user chooses something in the <select> the onChange should rather than doing a setConfigs to the backend instead change the displayForm boolean to true, and the component should rely on displayForm to know whether or not to display the form
2:29 PM
any changes that the component needs to know about that the rest of the world doesn't should move into the sign's state. so another example is the alert ID or the date time. those should now be new properties in the SignPanel state, and the callbacks should be updated in SetExpiration so that they don't send data to the backend, and instead just update the SignPanel's state. and then the Apply button should be updated to send to the backend the current values in the state

2021-08-12 14:15 UTC, losvedir commented
I slacked you these suggestions, but I'm going to post them here, too, so the PR reviewer has the context as well.

You'll have to refactor how the `SignPanel` component works.

React has the concept of "state", which is data that a component is responsible for internally, as opposed to "props" which is data that the component's parent gives it. What this ticket requires you to do is to move more stuff into the "state". Basically any changes that the component needs to know about that the rest of the app doesn't should be in the state.

Consider, as one part of this ticket, how changing the sign's mode from Auto -> Custom should open up the form without affecting the sign. Well, how did the component know whether or not to display the form beforehand?

```jsx
{signConfig.mode === 'static_text' && !readOnly && !signGroup && (
  <div className="viewer--static-text-form">
    <div>
      <strong>Set custom message</strong>
    </div>
// ...
```

This code only shows that markup if `signConfig.mode === 'static_text'`.  And what is `signConfig`?

```
interface SignPanelProps {
  // ...
  signConfig: SignConfig;
// ..
}
```

It's one of the props of the component. That's why currently the sign goes blank when you choose "custom".

```jsx
<select
  id={realtimeId}
  className="viewer--mode-select"
  value={signConfig.mode}
  onChange={(event) => {
    const newConfig = makeConfig(
      event.target.value as
        | 'auto'
        | 'headway'
        | 'off'
        | 'static_text',
    );
    this.setState({
      staticLine1: newConfig.line1 || '',
      staticLine2: newConfig.line2 || '',
      customChanges: false,
    });
    setConfigs({
      [realtimeId]: newConfig,
    });
  }}
>
```

When the user chooses something in the `<select>` the `onChange` fires, which calls `setConfigs(...)` which sends a request to the backend.

The flow of data goes from Phoenix backend -> ViewerApp -> ... -> Station -> SignPanel. And so selecting "custom" in the select updates the data in the backend, setting the sign's config to custom text with empty lines. And this data flows from the backend to the frontend and down the react app back to the SignPanel, and now the sign panel has in its props the fact that it's a custom text kind of sign, and so knows to display the form.

Getting back to one of the changes of this ticket: setting the `<select>` to "custom" and not blanking the sign because those changes haven't taken affect yet: that means we have to short circuit this whole "send to the backend and have the data flow back down through the props" approach. instead the `SignPanel` will have to have in its own state something like a boolean `displayForm`. And so now when the user chooses something in the `<select>` the `onChange` should rather than doing a `setConfigs` to the backend instead change the `displayForm` boolean to true, and the component should rely on `displayForm` to know whether or not to display the form.

Any changes that the component needs to know about that the rest of the world doesn't should move into the sign's state. So another example is the alert ID or the expiration datetime. Those should now be new properties in the SignPanel state, and the callbacks should be updated in `SetExpiration` so that they don't send data to the backend, and instead just update the SignPanel's state. and then the Apply button should be updated to send to the backend the current values in the state.

2023-03-07 19:43 UTC, panentheos commented
Hi all, this ticket is several years old and neither it nor the referenced ticket have been touched recently. Any objections to closing it?

2023-03-07 20:39 UTC, paulswartz commented
Not from me!

2023-03-09 13:56 UTC, closed without merging